import { StyleSheet } from 'react-native';
import { COLORES, SOMBRA, RADIO } from './globales';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORES.fondo },
  header: {
    backgroundColor: COLORES.primario,
    paddingTop: 55,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerTitulo: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
  headerSub: { color: COLORES.primarioClaro, fontSize: 13, marginTop: 4 },
  scroll: { padding: 20 },
  seccion: {
    backgroundColor: COLORES.fondoTarjeta,
    borderRadius: RADIO.lg,
    padding: 18,
    marginBottom: 16,
    ...SOMBRA,
  },
  seccionTitulo: {
    fontSize: 15,
    fontWeight: 'bold',
    color: COLORES.primario,
    marginBottom: 14,
  },
  label: { fontSize: 14, fontWeight: '600', color: COLORES.textoPrincipal, marginBottom: 6 },
  input: {
    backgroundColor: COLORES.fondo,
    borderWidth: 1.5,
    borderColor: COLORES.borde,
    borderRadius: RADIO.sm,
    padding: 12,
    fontSize: 15,
    color: COLORES.textoPrincipal,
    marginBottom: 14,
  },
  inputMultiline: { height: 90, textAlignVertical: 'top' },
  tiposContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  tipoBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: COLORES.borde,
    backgroundColor: COLORES.fondo,
  },
  tipoActivo: { borderColor: COLORES.primario, backgroundColor: COLORES.primarioClaro },
  tipoTexto: { color: COLORES.textoSecundario, fontSize: 13, fontWeight: '600' },
  tipoTextoActivo: { color: COLORES.primario },
  fotoBtn: {
    backgroundColor: COLORES.primarioClaro,
    borderRadius: RADIO.md,
    padding: 20,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORES.primario,
    borderStyle: 'dashed',
    marginBottom: 14,
  },
  fotoBtnIcono: { fontSize: 36, marginBottom: 6 },
  fotoBtnTexto: { color: COLORES.primario, fontWeight: '600', fontSize: 15 },
  fotoBtnSub: { color: COLORES.textoSecundario, fontSize: 12, marginTop: 2 },
  mapaPlaceholder: {
    backgroundColor: COLORES.primarioClaro,
    borderRadius: RADIO.md,
    height: 140,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORES.primario,
    borderStyle: 'dashed',
  },
  mapaIcono: { fontSize: 36, marginBottom: 6 },
  mapaTexto: { color: COLORES.primario, fontWeight: '600', fontSize: 15 },
  mapaSub: { color: COLORES.textoSecundario, fontSize: 12, marginTop: 2 },
  coordTexto: { color: COLORES.exito, fontSize: 13, marginTop: 8, textAlign: 'center', fontWeight: '600' },
  btnGuardar: {
    backgroundColor: COLORES.primario,
    padding: 17,
    borderRadius: RADIO.md,
    alignItems: 'center',
    marginBottom: 30,
    ...SOMBRA,
  },
  btnGuardarTexto: { color: '#fff', fontWeight: 'bold', fontSize: 17 },
});