import { StyleSheet } from 'react-native';
import { COLORES, SOMBRA, RADIO } from './globales';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORES.fondo },
  header: {
    backgroundColor: COLORES.primario,
    paddingTop: 55,
    paddingBottom: 20,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerTitulo: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
  btnAgregar: {
    backgroundColor: COLORES.acento,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: RADIO.md,
  },
  btnAgregarTexto: { color: '#fff', fontWeight: 'bold', fontSize: 13 },
  lista: { padding: 16, gap: 14 },
  tarjeta: {
    backgroundColor: COLORES.fondoTarjeta,
    borderRadius: RADIO.lg,
    overflow: 'hidden',
    ...SOMBRA,
  },
  tarjetaImagen: {
    width: '100%',
    height: 160,
    backgroundColor: COLORES.primarioClaro,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tarjetaImagenEmoji: { fontSize: 60 },
  tarjetaBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  badgeDisponible: { backgroundColor: COLORES.exito },
  badgeOcupada: { backgroundColor: COLORES.peligro },
  badgeTexto: { color: '#fff', fontSize: 11, fontWeight: 'bold' },
  tarjetaBody: { padding: 16 },
  tarjetaTitulo: { fontSize: 17, fontWeight: 'bold', color: COLORES.textoPrincipal },
  tarjetaDireccion: { fontSize: 13, color: COLORES.textoSecundario, marginTop: 4 },
  tarjetaPrecio: { fontSize: 20, fontWeight: 'bold', color: COLORES.primario, marginTop: 8 },
  tarjetaPrecioSub: { fontSize: 13, color: COLORES.textoSecundario },
  tarjetaAcciones: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: COLORES.borde,
  },
  btnEditar: {
    flex: 1,
    backgroundColor: COLORES.primarioClaro,
    padding: 10,
    borderRadius: RADIO.sm,
    alignItems: 'center',
  },
  btnEditarTexto: { color: COLORES.primario, fontWeight: '600', fontSize: 14 },
  btnEliminar: {
    flex: 1,
    backgroundColor: COLORES.peligroClaro,
    padding: 10,
    borderRadius: RADIO.sm,
    alignItems: 'center',
  },
  btnEliminarTexto: { color: COLORES.peligro, fontWeight: '600', fontSize: 14 },
  vacio: { alignItems: 'center', paddingTop: 80 },
  vacioIcono: { fontSize: 60, marginBottom: 16 },
  vacioTexto: { fontSize: 18, fontWeight: 'bold', color: COLORES.textoSecundario },
  vacioSub: { fontSize: 14, color: COLORES.textoClaro, marginTop: 6 },
});